M48
; DRILL file {KiCad 7.0.8} date Mo 23 Okt 2023 23:13:37 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-23T23:13:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X31.74Y-27.41
X31.74Y-33.19
T2
X27.5Y-12.0
X27.5Y-62.0
X122.5Y-12.0
X122.5Y-62.0
T0
M30
