M48
; DRILL file {KiCad (6.0.11)} date So 05 Feb 2023 23:01:44 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-05T23:01:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X31.74Y-27.41
X31.74Y-33.19
T2
X27.5Y-12.0
X27.5Y-62.0
X122.5Y-12.0
X122.5Y-62.0
T0
M30
